name: Laravel

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Composer Dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Set Up Environment
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Save Repository as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: source-code
          include-hidden-files: true
          path: |
            .
            !.env.production
            !.git
          retention-days: 1  # Optional: Set retention period for the artifact

  laravel-tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Download Repository Artifact
        uses: actions/download-artifact@v4
        with:
          name: source-code
          path: .

      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run Tests
        run: php artisan test

  style-check:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Download Repository Artifact
        uses: actions/download-artifact@v4
        with:
          name: source-code
          path: .

      - name: Run PhpCsFixer
        run: php vendor/bin/php-cs-fixer check --diff --config=.php-cs-fixer.php
